### PR TITLE
Fixed and updated using Exteplayer3, Gstplayer and Gstreamer for IPTV/VOD media

### PR DESCRIPTION
**Pull request by pepsik-kiev**

### CODE REVIEW

**Comment by persianpros** [comment]
Is this an old PR?

**Comment by MrServo** [comment]
**@pepsik-kiev**
Sorry for waiting so long!
Because we had a lot of work with the conversion from '**LCD4Linux**' to a Python 2+3 compatible combination, we have not yet been able to take care of your improvement. Unfortunately, you did not respond to the question whether your pull request is still valid or not and we do not have your email address. We have just built your modifications into the current Py2+3 test version and now let the users test and evaluate them. After this the community of **oe-alliance**- and/or **openATV**-users will decide whether your modification should be adopted or not. Thank you very much for your understanding.
Have a look here: https://www.opena.tv/plugins/73-lcd4linux-post469603.html#post469603
Kind regards.....Mr.Servo

**Comment by pepsik-kiev** [comment]
Hey ! I didn't answer for a long time - I was on vacation. Yes, all my changes are valid and used by many users. Especially in the vastness of the former USSR :). I saw the changes you made. At the moment, you have not transferred all the changes I made and it will not work in this form. 
Once you are done with code compatibility for Py2/Py3, I will transfer all my source codes and add a commit to your git after testing the code on Py2/Py3 (OpenATV 6.4/6.5)

THX  For your work  !

03 апреля 2021, 19:24:34, от Mr.Servo ***@***.***>:



@pepsik-kiev
Sorry for waiting so long!
Because we had a lot of work with the conversion from 'LCD4Linux' to a Python 2+3 compatible combination, we have not yet been able to take care of your improvement. Unfortunately, you did not respond to the question whether your pull request is still valid or not and we do not have your email address. We have just built your modifications into the current Py2+3 test version and now let the users test and evaluate them. After this the community of oe-alliance- and/or openATV-users will decide whether your modification should be adopted or not. Thank you very much for your understanding.
Have a look here: https://www.opena.tv/plugins/73-lcd4linux-post469603.html#post469603
Kind regards.....Mr.Servo

**Comment by MrServo** [comment]
Hi pepsik!
Oh, you've found a bug in the current L4L-version? Where?
On the other hand: Of course we are interested in a proper version, so we appreciate your Pullrequest with the corrections.
Please note, that the author (originator) **joergm6 @ IHAD** have sent us his version of additional audioicons that we have implemented. Most of the user find them "nicer" and "better readable".
Regards.....Mr.Servo

**Comment by MrServo** [comment]
**>> Once you are done with code compatibility for Py2/Py3, I will transfer all my source codes and add a commit to your git after testing the code on Py2/Py3 (OpenATV 6.4/6.5)**
Hi pepsik!
We are ready for the moment, all known Py2/3-bugs are fixed and you can fork the repo now and place your pullrequest if you want. Please note, that we -as I wrote- will use the golden audioicons from **joergm6@IHAD** instead your blue audioicons. Sorry for that...
Thank your very much for improving LCD4linix......Mr.Servo

**Pull request closed without merging**
