### PR TITLE
LCD4linux: PEP8 double aggressive E20 and E211

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by persianpros** [comment]
Better to re-check the plugin after merging the new version.

**Comment by jbleyel** [comment]
Hi @persianpros , there is also your autopep8 script in travis.
-> https://github.com/oe-alliance/oe-alliance-plugins/blob/python3/PEP8.sh

You probably use a different version of autopep8.

**Comment by persianpros** [comment]
@jbleyel 

Oh I didn't check python3 branch and https://github.com/oe-alliance/oe-alliance-plugins/commit/44ce530eb622341c7aec7d08f3111a7e8afbde62

Nice to see you add this to all repos and the future commits will be cleaned up :+1: 

I thank you for being so supportive about this.

Also I didn't send any PR for https://github.com/oe-alliance/TerrestrialScan and https://github.com/oe-alliance/MisPlsLcnScan (and ViX repos) as Huevos and RobvanderDoes are managing those repos and they just don't like me so better if you do it.

You may want to check https://github.com/openatv/enigma2-plugin-extensions-dbackup/pulls and https://github.com/openatv/enigma2-plugin-extensions-dflash/pulls as well.

**Comment by jbleyel** [comment]
Please do the last 2 pulls for the python3 branch too.

**Comment by jbleyel** [comment]
Hi @persianpros, do you use an python3 image of OpenVision?
How can i build this for my box?

**Comment by persianpros** [comment]
@jbleyel 

No not yet, we didn't go to py3 yet but we will.

What's your box? I can compile it for you or I can give you access to our private OE so you build it yourself, your call :+1:

**Comment by jbleyel** [comment]
I wanna do it by myself if possible.
But why do u use private repro?

**Comment by persianpros** [comment]
@jbleyel 

https://openvision.tech/?p=210

Only our OEs are private, the rest are open/public.

**Comment by jbleyel** [comment]
can i get access? .. you can contact me via mail

**Comment by persianpros** [comment]
@jbleyel 

You have now ;)

https://github.com/OpenVisionE2/openvision-development-platform for new models: https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/Vision-metas.md

https://github.com/OpenVisionE2/openvision-oe for old models: https://github.com/OpenVisionE2/openvision-oe/blob/develop/Vision-metas.md

You just need to run our image.sh and do what you desire.

**Comment by jbleyel** [comment]
Thanks ..

**Comment by RobvanderDoes** [comment]
> Also I didn't send any PR for https://github.com/oe-alliance/TerrestrialScan and https://github.com/oe-alliance/MisPlsLcnScan (and ViX repos) as Huevos and RobvanderDoes are managing those repos and they just don't like me so better if you do it.


You are sooo wrong: we all love you, we love you very, very much!

But: maintaining a repro doesn't have anything to do with (not) liking some one, so not sure why you write this.....

**Pull request closed without merging**
