### PR TITLE
Update v5.0-r5a

### PR DESCRIPTION
**Pull request by MrServo**
### New Features for LCD4Linux V5.0-r5a:

- now also rectangular clockfaces are supported (previously only square clockfaces)

- Gaps between the clocknames in folder "data" are now allowed. Default clock is the first clockname found.
   Example with only 3 clocknames in folder "data" (default will be Clock2 then):
   Clock2
   Clock8
   Clock9

- already existing Clock7 (512x512 - ratio 1:1) has been activated

- rectangle Clock8 (220x176 - ratio 5:4), Clock9 (400x240 - ratio 5:3) and Clock10 (480x320 - ratio 3:2) has been added and activated

- rectangle Clock11-28 has been added but not activated and remain ready for indivudial download

Details about the design of new clockfaces: www.opena.tv/plugins/73-lcd4linux-post462967.html#post462967

### CODE REVIEW

**Comment by jbleyel** [comment]
Please make the update for the PY3 dev branch too.
Thanks

**Comment by MrServo** [comment]
Hi jbleyel,
**Attention:** LCD4Linux V5.0-r5a is ONLY working under Python 2. The existing LCD4Linux V5.0-r7 in Branch DEV has only 'untested' status and it crashes when using it. I've tried to debug this PY2/3-Dualversion '-r7' but I couldn't solve all problems in this -r7. Main Problem: The -r7 under PY3 can't talk to the LCD-Displays and here are other problems of the PY2/3-Dualversion (when it works on PY3, then not correct under PY2 and vice-versa). See here (in German): https://www.opena.tv/plugins/73-lcd4linux-post463817.html#post463817
Regards......Mr.Servo

**Comment by jbleyel** [comment]
My fault.
By why not r7 PY2 in master branch?

**Comment by jbleyel** [comment]
I have made the PY3 version but i cannot test all the features.
I do not have any crashes on my 6.5 Box.

**Comment by MrServo** [comment]
Hi jbleyel
The -r7 in DEV-branch crashes when configurating and using the L4L-WebIF. Several users have reported this (see my link above). Even when I have removed a lot of bugs, I can't find all errors (e.g. missing 'GUI restart' message and crashing WebIF " Processing failed ").
this leads to " Processing failed ": https://www.opena.tv/plugins/73-lcd4linux-post463807.html#post463807
see also here: www.opena.tv/plugins/73-lcd4linux-post463175.html#post463175
Some errors I could eleminate in -r7 but not all (my latest testversion **-r7c** is here in Github: https://github.com/MrServo/oe-alliance-plugins/tree/update-V5.0-r8.
Regards.....Mr.Servo

**Comment by MrServo** [comment]
Hi jbleyel,
If you like I can forward you a summary of all modifications I've made (debugging) and I can assist you with finishing L4L-r8.
Im am in correspondence with the author of LCD4Linux (joergm6@IHAD or jockelm6@OpenATV) and he told me his next dreambox-release will be the "V5.1".  He is still on PY2.
What's you opinion?
Regards......Mr.Servo

**Pull request merged**
