### PR TITLE
[ABMCustomMixImporter] fix attribute 'setup_tittle' error

### PR DESCRIPTION
**Pull request by davesayers2014**
Hopefully this should fix crash

### CODE REVIEW

**Comment by Huevos** [comment]
What do yo mean "hopefully"? Is it a tested solution?

**Comment by davesayers2014** [comment]
Yes and it works fine for me sorry for my bad wording

**Comment by davesayers2014** [comment]
Ok im not sure whats happening now im getting 
abm custommix importer responce 200

Debug Log 

< 93042.284> [ActionMap] ColorActions yellow
< 93042.316> [ABMCustomMixImporter][__init__] Starting...
< 93042.319> [Skin] processing screen AutoBouquetsMaker:
< 93042.320> [Skin] Skin error in screen 'AutoBouquetsMaker' widget 'widget': [Skin] {vskin-hd/skin.xml}: component with name 'progress' was not found in skin of screen 'AutoBouquetsMaker'!. Please contact the skin's author!
< 93042.322> [Skin] Parsing embedded skin <embedded-in-'SimpleSummary'>
< 93042.322> [Skin] processing screen <embedded-in-'SimpleSummary'>:
< 93042.445> [ABMCustomMixImporter][fetchURL] Response: 200
< 93042.474> [Skin] processing screen MessageBox:
< 93042.485> [Skin] Parsing embedded skin <embedded-in-'SimpleSummary'>
< 93042.486> [Skin] processing screen <embedded-in-'SimpleSummary'>:
< 93042.490> [ABMCustomMixImporter]Saving file failed.

This maybe a local issue ill close this pull request till I am sure this is an issue my end

**Comment by davesayers2014** [comment]
Line 157 was still with open(ABMpath + mixes[config.plugins.ABMImporter.mix.value]["provider"] 

It should be lower case abm

**Pull request closed without merging**
